-- Initial schema for booking system
-- Run this with: npx wrangler d1 execute knapgemaakt-bookings --local --file=./migrations/0001_initial_schema.sql
-- For production: npx wrangler d1 execute knapgemaakt-bookings --remote --file=./migrations/0001_initial_schema.sql

-- Availability rules (your business hours)
CREATE TABLE IF NOT EXISTS availability_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day_of_week INTEGER NOT NULL, -- 0 = Monday, 6 = Sunday
  start_time TEXT NOT NULL,      -- "09:00"
  end_time TEXT NOT NULL,        -- "17:00"
  slot_duration INTEGER NOT NULL DEFAULT 15, -- minutes
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- User bookings
CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,           -- UUID generated by API
  user_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  user_phone TEXT NOT NULL,
  user_company TEXT,
  user_industry TEXT,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmed', -- "confirmed" | "cancelled"
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Blocked times (synced from Google Calendar)
CREATE TABLE IF NOT EXISTS blocked_times (
  id TEXT PRIMARY KEY,           -- Google Calendar event ID
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  source TEXT NOT NULL,          -- "google_calendar" | "manual"
  calendar_event_id TEXT,        -- Original Google Calendar event ID
  synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bookings_start_time ON bookings(start_time);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_blocked_times_start_time ON blocked_times(start_time);
CREATE INDEX IF NOT EXISTS idx_availability_rules_day ON availability_rules(day_of_week);

-- Insert default availability rules (Monday-Friday, 9:00-17:00, 15-minute slots)
INSERT INTO availability_rules (day_of_week, start_time, end_time, slot_duration) VALUES
  (0, '09:00', '17:00', 15), -- Monday
  (1, '09:00', '17:00', 15), -- Tuesday
  (2, '09:00', '17:00', 15), -- Wednesday
  (3, '09:00', '17:00', 15), -- Thursday
  (4, '09:00', '17:00', 15); -- Friday
